apiVersion: v1
kind: ServiceAccount
metadata:
  name: riskcast-api
  namespace: riskcast
  labels:
    app: riskcast-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: riskcast-worker
  namespace: riskcast
  labels:
    app: riskcast-worker
