#!/usr/bin/env python3
"""
Deterministic LOC counter (repo-root runnable).

Outputs:
  - ./artifacts/loc_report.json
  - ./artifacts/loc_report.csv

Constraints:
  - Does NOT modify repository content (only writes under ./artifacts/)
  - Deterministic file traversal + stable output ordering
"""

from __future__ import annotations

import csv
import hashlib
import json
import os
import platform
import re
import shutil
import stat
import subprocess
import sys
import tempfile
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

# =============================================================================
# EXCLUSIONS (edit here)
# =============================================================================

EXCLUDE_DIRS = {
    "node_modules",
    "dist",
    "build",
    ".next",
    ".nuxt",
    "coverage",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    "venv",
    "env",
    "__pycache__",
    "logs",
    "tmp",
    ".git",
}

EXCLUDE_FILE_NAMES = {
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "poetry.lock",
    "pipfile.lock",
    "uv.lock",
}

EXCLUDE_GLOBS_RE = [
    re.compile(r".*\.min\.js$", re.IGNORECASE),
    re.compile(r".*\.min\.css$", re.IGNORECASE),
]

EXCLUDE_EXTENSIONS = {
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".pdf",
    ".zip",
    ".tar",
    ".gz",
    ".7z",
    ".mp4",
    ".mov",
    ".avi",
    ".bin",
}

# =============================================================================
# LANGUAGE DETECTION
# =============================================================================

LANGUAGE_BY_EXT = {
    ".py": "Python",
    ".ts": "TypeScript",
    ".tsx": "TSX",
    ".js": "JavaScript",
    ".mjs": "JavaScript",
    ".cjs": "JavaScript",
    ".vue": "Vue",
    ".html": "HTML",
    ".htm": "HTML",
    ".css": "CSS",
    ".scss": "CSS",
    ".sass": "CSS",
    ".less": "CSS",
    ".sql": "SQL",
    ".yml": "YAML",
    ".yaml": "YAML",
    ".md": "Markdown",
    ".markdown": "Markdown",
}


def detect_language(path: Path) -> Optional[str]:
    name = path.name
    if name == "Dockerfile":
        return "Dockerfile"
    ext = path.suffix.lower()
    return LANGUAGE_BY_EXT.get(ext)


def is_docs_language(lang: str) -> bool:
    return lang == "Markdown"


def is_migration_file(path: Path) -> bool:
    # Common patterns: alembic migrations under migrations/versions/*.py etc.
    parts = [p.lower() for p in path.parts]
    if "migrations" in parts or "alembic" in parts:
        return True
    # Django migrations convention
    if any(p == "migrations" for p in parts) and path.suffix.lower() == ".py":
        return True
    return False


AUTO_GENERATED_MARKERS_RE = re.compile(
    r"(auto-?generated|generated by|this file is generated|do not edit|autogenerated)",
    re.IGNORECASE,
)


def is_reliably_autogenerated_migration(path: Path, content: str) -> bool:
    """
    Only exclude migrations if we can detect reliably they are auto-generated.
    Heuristic: contains strong "generated/do not edit" markers near the top.
    """
    if not is_migration_file(path):
        return False
    head = "\n".join(content.splitlines()[:50])
    return bool(AUTO_GENERATED_MARKERS_RE.search(head))


# =============================================================================
# LINE CLASSIFICATION
# =============================================================================

TRIPLE_QUOTE_RE = re.compile(r"(^|[^\\])('''|\"\"\")")


def _split_lines_newline_counting(text: str) -> List[str]:
    # Standard LOC: newline separators.
    # splitlines() would drop the trailing empty line; using split("\n") matches the earlier behavior.
    return text.split("\n")


def count_python(text: str) -> Tuple[int, int, int]:
    """
    Python rules:
      - line starting with # (after whitespace) is a comment
      - docstrings counted as comments only if standalone triple-quoted blocks not assigned to variables
    Notes:
      This is a lightweight state machine; it won't perfectly parse Python but is deterministic.
    """
    code = comment = blank = 0
    in_doc = False
    doc_delim: Optional[str] = None

    for line in _split_lines_newline_counting(text):
        raw = line
        s = raw.strip()
        if s == "":
            blank += 1
            continue

        # docstring block handling
        if in_doc:
            comment += 1
            if doc_delim and doc_delim in raw:
                # close if odd count on this line
                if raw.count(doc_delim) % 2 == 1:
                    in_doc = False
                    doc_delim = None
            continue

        ws = raw.lstrip()
        if ws.startswith("#"):
            comment += 1
            continue

        # detect standalone docstring start:
        # - must start with triple quote after whitespace
        # - must NOT look like assignment: x = """..."""
        if ws.startswith('"""') or ws.startswith("'''"):
            # If it's on a line that also contains an assignment before it, don't treat as docstring.
            # (we already used lstrip so this excludes leading whitespace; assignment would be in ws)
            if "=" not in ws.split(ws[:3])[0]:
                comment += 1
                delim = ws[:3]
                # single-line docstring """foo"""
                if ws.count(delim) >= 2 and ws.count(delim) % 2 == 0:
                    in_doc = False
                    doc_delim = None
                else:
                    in_doc = True
                    doc_delim = delim
                continue

        code += 1

    return code, comment, blank


def count_c_like(text: str, line_comment: str = "//") -> Tuple[int, int, int]:
    code = comment = blank = 0
    in_block = False
    for line in _split_lines_newline_counting(text):
        s = line.strip()
        if s == "":
            blank += 1
            continue

        if in_block:
            comment += 1
            if "*/" in line:
                in_block = False
            continue

        if s.startswith(line_comment):
            comment += 1
            continue

        if "/*" in line:
            comment += 1
            if "*/" not in line or (line.find("/*") > line.find("*/")):
                in_block = True
            continue

        code += 1
    return code, comment, blank


def count_yaml(text: str) -> Tuple[int, int, int]:
    code = comment = blank = 0
    for line in _split_lines_newline_counting(text):
        if line.strip() == "":
            blank += 1
            continue
        if line.lstrip().startswith("#"):
            comment += 1
        else:
            code += 1
    return code, comment, blank


def count_markdown(text: str) -> Tuple[int, int, int]:
    # For reporting: docs bucket, no comment parsing.
    code = comment = blank = 0
    for line in _split_lines_newline_counting(text):
        if line.strip() == "":
            blank += 1
        else:
            code += 1
    return code, comment, blank


VUE_BLOCK_RE = re.compile(r"<(?P<tag>template|script|style)(?P<attrs>[^>]*)>(?P<body>.*?)</\1>", re.I | re.S)


def count_vue(text: str) -> Dict[str, Tuple[int, int, int]]:
    """
    Vue SFC: count <template>, <script>, <style> separately and tag them:
      - Vue:template
      - Vue:script
      - Vue:style
    """
    counts: Dict[str, Tuple[int, int, int]] = {}
    for m in VUE_BLOCK_RE.finditer(text):
        tag = m.group("tag").lower()
        body = m.group("body") or ""
        if tag == "script":
            counts["Vue:script"] = count_c_like(body, line_comment="//")
        elif tag == "template":
            # HTML comments <!-- --> are treated as comments; simplified as code-only here to avoid overcounting
            counts["Vue:template"] = count_c_like(body, line_comment="<!--")  # pragmatic approximation
        elif tag == "style":
            counts["Vue:style"] = count_c_like(body, line_comment="/*")  # will be handled by block logic
    if not counts:
        counts["Vue"] = count_c_like(text, line_comment="//")
    return counts


# =============================================================================
# SCANNING + REPORTING
# =============================================================================


@dataclass(frozen=True)
class FileStats:
    path: str
    language: str
    code_lines: int
    comment_lines: int
    blank_lines: int
    total_lines: int


def should_exclude_path(path: Path, repo_root: Path) -> bool:
    rel = path.relative_to(repo_root)

    for part in rel.parts:
        if part in EXCLUDE_DIRS:
            return True

    if path.name in EXCLUDE_FILE_NAMES:
        return True

    if path.suffix.lower() in EXCLUDE_EXTENSIONS:
        return True

    rel_s = str(rel).replace("\\", "/")
    for rx in EXCLUDE_GLOBS_RE:
        if rx.match(rel_s):
            return True

    return False


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="ignore")


def count_file(path: Path, lang: str, repo_root: Path) -> List[FileStats]:
    text = read_text(path)

    # Migrations rule: exclude only if reliably auto-generated.
    if is_reliably_autogenerated_migration(path, text):
        return []

    # Otherwise: include migrations, but with separate bucket "migrations"
    lang_bucket = lang
    if is_migration_file(path):
        lang_bucket = "migrations"

    if lang == "Python":
        c, cm, b = count_python(text)
        return [FileStats(str(path.relative_to(repo_root)), lang_bucket, c, cm, b, c + cm + b)]

    if lang in ("JavaScript", "TypeScript", "TSX", "HTML", "CSS", "SQL", "Dockerfile"):
        if lang == "SQL":
            c, cm, b = count_c_like(text, line_comment="--")
        elif lang == "CSS":
            c, cm, b = count_c_like(text, line_comment="/*")
        elif lang == "HTML":
            c, cm, b = count_c_like(text, line_comment="<!--")
        else:
            c, cm, b = count_c_like(text, line_comment="//")
        return [FileStats(str(path.relative_to(repo_root)), lang_bucket, c, cm, b, c + cm + b)]

    if lang == "YAML":
        c, cm, b = count_yaml(text)
        return [FileStats(str(path.relative_to(repo_root)), lang_bucket, c, cm, b, c + cm + b)]

    if lang == "Markdown":
        c, cm, b = count_markdown(text)
        # report separately as docs (not code)
        return [FileStats(str(path.relative_to(repo_root)), "docs", c, cm, b, c + cm + b)]

    if lang == "Vue":
        out: List[FileStats] = []
        for sublang, (c, cm, b) in count_vue(text).items():
            out.append(
                FileStats(str(path.relative_to(repo_root)), f"{lang_bucket}:{sublang.split(':')[-1]}", c, cm, b, c + cm + b)
            )
        return out

    return []


def aggregate(file_stats: List[FileStats]) -> Dict[str, Dict[str, int]]:
    agg: Dict[str, Dict[str, int]] = {}
    for s in file_stats:
        if s.language not in agg:
            agg[s.language] = {"code_lines": 0, "comment_lines": 0, "blank_lines": 0, "files_count": 0, "total_lines": 0}
        agg[s.language]["code_lines"] += s.code_lines
        agg[s.language]["comment_lines"] += s.comment_lines
        agg[s.language]["blank_lines"] += s.blank_lines
        agg[s.language]["total_lines"] += s.total_lines
        agg[s.language]["files_count"] += 1
    return agg


def stable_walk_files(repo_root: Path) -> Iterable[Path]:
    # Deterministic traversal: sort directories and files lexicographically.
    for dirpath, dirnames, filenames in os.walk(repo_root):
        dirnames.sort()
        filenames.sort()
        base = Path(dirpath)
        for fn in filenames:
            yield base / fn


# =============================================================================
# CROSS-CHECK (scc preferred, optional download)
# =============================================================================


def sha256_file(p: Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def download_scc_binary(dest: Path) -> Optional[Path]:
    """
    Attempt to download scc from GitHub releases.
    We fetch the latest tag page (static 'latest') and then use a conservative filename strategy.
    If the pattern isn't found, we skip.
    """
    latest_url = "https://github.com/boyter/scc/releases/latest"
    try:
        with urllib.request.urlopen(latest_url, timeout=20) as resp:
            html = resp.read().decode("utf-8", errors="ignore")
    except Exception:
        return None

    sysname = platform.system().lower()
    machine = platform.machine().lower()

    if sysname.startswith("win"):
        os_token = "windows"
        ext = ".zip"
    elif sysname == "darwin":
        os_token = "darwin"
        ext = ".tar.gz"
    else:
        os_token = "linux"
        ext = ".tar.gz"

    if machine in ("x86_64", "amd64"):
        arch_token = "amd64"
    elif machine in ("aarch64", "arm64"):
        arch_token = "arm64"
    else:
        return None

    # Look for an asset link containing both tokens.
    # Example expected patterns include: scc_..._<os>_<arch>.tar.gz or scc-...-<os>-<arch>.zip
    rx = re.compile(r'href=\"(?P<href>/boyter/scc/releases/download/[^\\\"]+%s[^\\\"]*%s[^\\\"]*%s)\"' % (os_token, arch_token, re.escape(ext)))
    m = rx.search(html)
    if not m:
        # fallback: allow either order
        rx2 = re.compile(r'href=\"(?P<href>/boyter/scc/releases/download/[^\\\"]+%s[^\\\"]*%s[^\\\"]*%s)\"' % (arch_token, os_token, re.escape(ext)))
        m = rx2.search(html)
        if not m:
            return None

    asset_path = m.group("href").replace("&amp;", "&")
    asset_url = "https://github.com" + asset_path

    dest.parent.mkdir(parents=True, exist_ok=True)
    try:
        with urllib.request.urlopen(asset_url, timeout=60) as resp, dest.open("wb") as f:
            shutil.copyfileobj(resp, f)
    except Exception:
        return None
    return dest


def extract_scc(archive: Path, workdir: Path) -> Optional[Path]:
    sysname = platform.system().lower()
    try:
        if sysname.startswith("win"):
            import zipfile

            with zipfile.ZipFile(archive, "r") as z:
                z.extractall(workdir)
        else:
            import tarfile

            with tarfile.open(archive, "r:gz") as t:
                t.extractall(workdir)
    except Exception:
        return None

    # Find executable named scc or scc.exe
    for p in workdir.rglob("*"):
        if p.is_file() and p.name in ("scc", "scc.exe"):
            if not sysname.startswith("win"):
                p.chmod(p.stat().st_mode | stat.S_IXUSR)
            return p
    return None


def run_scc(repo_root: Path) -> Optional[dict]:
    scc = shutil.which("scc")
    if scc:
        try:
            out = subprocess.check_output([scc, "--format", "json", str(repo_root)], text=True)
            return {"tool": "scc", "raw_json": out}
        except Exception:
            return None

    # Attempt download
    with tempfile.TemporaryDirectory() as td:
        td_path = Path(td)
        archive = td_path / "scc_download"
        downloaded = download_scc_binary(archive)
        if not downloaded:
            return None
        extracted = extract_scc(downloaded, td_path / "extracted")
        if not extracted:
            return None
        try:
            out = subprocess.check_output([str(extracted), "--format", "json", str(repo_root)], text=True)
            return {
                "tool": "scc(downloaded)",
                "raw_json": out,
                "archive_sha256": sha256_file(downloaded),
            }
        except Exception:
            return None


# =============================================================================
# OUTPUT
# =============================================================================


def write_reports(artifacts_dir: Path, file_stats: List[FileStats], agg: Dict[str, Dict[str, int]]) -> Tuple[Path, Path, dict]:
    artifacts_dir.mkdir(parents=True, exist_ok=True)
    csv_path = artifacts_dir / "loc_report.csv"
    json_path = artifacts_dir / "loc_report.json"

    total_code = sum(s.code_lines for s in file_stats)
    total_comment = sum(s.comment_lines for s in file_stats)
    total_blank = sum(s.blank_lines for s in file_stats)

    by_lang_rows = [
        {
            "language": lang,
            **vals,
        }
        for lang, vals in agg.items()
    ]
    by_lang_rows.sort(key=lambda r: (-r["code_lines"], r["language"]))

    top_files = sorted(file_stats, key=lambda s: (-s.code_lines, s.path))[:50]

    report = {
        "summary": {
            "total_code_lines": total_code,
            "total_comment_lines": total_comment,
            "total_blank_lines": total_blank,
            "total_lines": total_code + total_comment + total_blank,
            "total_files": len(file_stats),
        },
        "by_language": by_lang_rows,
        "top_50_files": [
            {
                "path": s.path,
                "language": s.language,
                "code_lines": s.code_lines,
                "comment_lines": s.comment_lines,
                "blank_lines": s.blank_lines,
                "total_lines": s.total_lines,
            }
            for s in top_files
        ],
    }

    json_path.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    with csv_path.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["Language", "code_lines", "comment_lines", "blank_lines", "total_lines", "files_count"])
        for r in by_lang_rows:
            w.writerow([r["language"], r["code_lines"], r["comment_lines"], r["blank_lines"], r["total_lines"], r["files_count"]])
        w.writerow([])
        w.writerow(["Top 50 largest files by code_lines"])
        w.writerow(["path", "language", "code_lines", "comment_lines", "blank_lines", "total_lines"])
        for s in top_files:
            w.writerow([s.path, s.language, s.code_lines, s.comment_lines, s.blank_lines, s.total_lines])

    return json_path, csv_path, report


def print_summary(report: dict, cross: Optional[dict]) -> None:
    s = report["summary"]
    print("=" * 80)
    print("LOC REPORT")
    print("=" * 80)
    print(f"Total LOC (code):     {s['total_code_lines']:,}")
    print(f"Total comment lines:  {s['total_comment_lines']:,}")
    print(f"Total blank lines:    {s['total_blank_lines']:,}")
    print(f"Total lines:          {s['total_lines']:,}")
    print(f"Files counted:        {s['total_files']:,}")
    print()
    print(f"{'Language':<22} {'code':>12} {'comment':>12} {'blank':>12} {'total':>12} {'files':>8}")
    print("-" * 80)
    for r in report["by_language"]:
        print(
            f"{r['language']:<22} {r['code_lines']:>12,} {r['comment_lines']:>12,} {r['blank_lines']:>12,} {r['total_lines']:>12,} {r['files_count']:>8,}"
        )
    print()

    if cross:
        print("Cross-check:")
        print(f"  tool: {cross.get('tool')}")
        if cross.get("archive_sha256"):
            print(f"  downloaded archive sha256: {cross['archive_sha256']}")
    else:
        print("Cross-check: skipped (scc not found and download unavailable)")


def main() -> int:
    repo_root = Path.cwd().resolve()
    artifacts_dir = repo_root / "artifacts"

    file_stats: List[FileStats] = []

    for path in stable_walk_files(repo_root):
        if not path.is_file():
            continue
        if should_exclude_path(path, repo_root):
            continue

        lang = detect_language(path)
        if not lang:
            continue

        # Never count artifacts outputs themselves
        if str(path.relative_to(repo_root)).replace("\\", "/").startswith("artifacts/"):
            continue

        file_stats.extend(count_file(path, lang, repo_root))

    agg = aggregate(file_stats)
    json_path, csv_path, report = write_reports(artifacts_dir, file_stats, agg)

    cross = run_scc(repo_root)
    # If we have scc output, try to compare code total (best-effort).
    if cross and "raw_json" in cross:
        try:
            scc_data = json.loads(cross["raw_json"])
            # scc JSON formats can vary; best effort: sum over language entries if present.
            scc_code = None
            if isinstance(scc_data, dict) and "languageSummary" in scc_data:
                scc_code = sum(int(x.get("Code", 0)) for x in scc_data["languageSummary"])
            if scc_code is not None:
                ours = report["summary"]["total_code_lines"]
                diff_pct = abs(scc_code - ours) / max(scc_code, ours) * 100 if max(scc_code, ours) else 0.0
                cross["scc_total_code_lines"] = scc_code
                cross["ours_total_code_lines"] = ours
                cross["diff_pct"] = diff_pct
                if diff_pct > 2.0:
                    cross["explanation"] = (
                        "Difference >2% likely due to: docstring classification, Vue sub-bucketing, "
                        "migration bucketing, or different ignore semantics."
                    )
        except Exception:
            pass

    # Re-write JSON to include cross-check metadata (still under artifacts/)
    report["cross_check"] = cross
    json_path.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    print_summary(report, cross)
    print()
    print(f"Wrote: {json_path}")
    print(f"Wrote: {csv_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
